### ISSUE TITLE
Migrate todo to github

### ISSUE THREAD

**Issue by cratuki** [cratuki/solent#5]
Summary: Upcoming work should be captured either in tasks, or in org-file documents. Working out the balance of this is part of the work to be done in this task.

Background: Currently I'm running my todo through my personal system.

**Comment by petr-tik** [comment]
If you want to build a community, you need to lower the barriers to entry - it should be easy for people to:

- [x] to look at the code - on GitHub
- [ ] to look at issues
- [ ] to send patches - for you to merge them quickly, they should be small incremental changes that you can review and ok easily. It's a pain for you to review massive changes that complete the whole project, but possibly
- [ ] ensure quality - ideally have a CI suite that runs tests on each commit, so at every point the master is a working artefact

**Comment by cratuki** [comment]
This is excellent. I've been meaning to get my thoughts better organised on these topics, and what you're saying here resonates. Thanks.

I don't yet understand how merging works. I've created a new ticket to work out policies for these. (or it might be trivial - maybe just something I need to understand) Excuse me for not acting on them immediately - I'm in the swamp with something at the moment. This conversation has been significant progress all the same.
